version: 2
jobs:
  build:
    docker:
      - image: gcc:latest
    steps:
      - checkout
      - run:
          name: Build source
          command: g++ -std=c++11 test.cpp -o test.out
      - run:
          name: Run
          command: ./test.out
workflows:
  version: 2
  build:
    jobs:
      - build
